### ISSUE TITLE
sanitizeErrorMessage fails

### ISSUE THREAD

**Issue by Linearity** [webdriverio/wdio-sync#50]
https://github.com/webdriverio/wdio-sync/blob/master/index.js#L38

When running browser-automation tests with Chimp, which depends on wdio-sync, the above line is producing an exception:
```
 Uncaught TypeError: Cannot read property 'trim' of undefined
      at sanitizeErrorMessage (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:87:34)
      at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:337:53)
      at Context.<anonymous> (tests/e-suite.js:48:13)
      at /usr/local/lib/node_modules/chimp/dist/lib/utils/fiberize.js:24:12
```
The wdio-sync code assumes that the call stack is an `Array` with some element that can be `shift`ed off. That condition is apparently not guaranteed.

**Comment by christian-bromann** [comment]
> That condition is apparently not guaranteed.

Probably because all stack trace lines are filtered by [`STACKTRACE_FILTER`](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L9). I would not consider this to be an issue with wdio-sync. It seems that the chimp framework errors messages does not contain any stack trace line that points to a file outside of the node_modules directory. I believe this condition has to be fulfilled.

However I would consider a PR.
Thanks
